exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("projects")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("projects").insert([
        {
          id: 1,
          title: "Project 1",
          type: "Web Development",
          description: "Description of Project 1",
          image_source: "https://via.placeholder.com/150",
          link: "https://github.com/imanhedeshy/project1",
          user_id: 3,
        },
        {
          id: 2,
          title: "Project 2",
          type: "Mobile App Development",
          description: "Description of Project 2",
          image_source: "https://via.placeholder.com/150",
          link: "https://github.com/johndoe/project2",
          user_id: 2,
        },
        {
          id: 3,
          title: "Project 10",
          type: "Data Science",
          description: "Description of Project 10",
          image_source: "https://via.placeholder.com/150",
          link: "https://github.com/janedoe/project10",
          user_id: 3,
        },
        {
          id: 4,
          title: "The BOX!",
          type: "capstone",
          description: "project_description",
          image_source: "https://via.placeholder.com/150",
          link: "project_link",
          user_id: 1,
        },
        {
          id: 5,
          title: "BrainStationFlix",
          type: "hackathon",
          description: "project_description",
          image_source: "project_image_source",
          link: "project_link",
          user_id: 1,
        },
        {
          id: 6,
          title: "TritonPrivacyVault",
          type: "hackathon",
          description: "project_description",
          image_source: "project_image_source",
          link: "project_link",
          user_id: 1,
        },
        {
          id: 7,
          title: "MooCooCaw",
          type: "hackathon",
          description: "project_description",
          image_source: "project_image_source",
          link: "project_link",
          user_id: 1,
        },
        {
          id: 8,
          title: "BandSite",
          type: "student_project",
          description: "project_description",
          image_source: "project_image_source",
          link: "project_link",
          user_id: 1,
        },
        {
          id: 9,
          title: "BrainFlix",
          type: "student_project",
          description: "project_description",
          image_source: "project_image_source",
          link: "project_link",
          user_id: 1,
        },
        {
          id: 10,
          title: "InStock",
          type: "student_project",
          description: "project_description",
          image_source: "project_image_source",
          link: "project_link",
          user_id: 1,
        },
        {
          id: 11,
          title: "Solar System",
          type: "personal_project",
          description: "project_description",
          image_source: "project_image_source",
          link: "project_link",
          user_id: 1,
        },
        {
          id: 12,
          title: "File Structure Viewer",
          type: "personal_project",
          description: "project_description",
          image_source: "project_image_source",
          link: "project_link",
          user_id: 1,
        },
        {
          id: 13,
          title: "Journal",
          type: "personal_project",
          description: "project_description",
          image_source: "project_image_source",
          link: "project_link",
          user_id: 1,
        },
      ]);
    });
};
